# Generated by Django 4.1.10 on 2023-11-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="analyse",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="lungdiagnostic.analyses",
            ),
        ),
        migrations.AlterField(
            model_name="treatement",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="lungdiagnostic.patient"
            ),
        ),
        migrations.DeleteModel(
            name="Collaboration",
        ),
    ]
