# Generated by Django 4.1.10 on 2023-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0003_alter_treatement_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="medcine",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
