# Generated by Django 4.1.10 on 2023-11-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0004_remove_patient_phone_number_alter_medcine_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medcine",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="medcine",
            name="occupation",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
