# Generated by Django 4.1.10 on 2023-11-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0009_remove_medcine_organization_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medcine",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="D:\\fin_de_etude\\data\\pfe\\back end\\application\\media",
            ),
        ),
    ]
