# Generated by Django 4.1.10 on 2023-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0014_alter_patient_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
    ]
