# Generated by Django 4.1.10 on 2023-11-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "lungdiagnostic",
            "0002_alter_report_analyse_alter_treatement_patient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatement",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lungdiagnostic.patient"
            ),
        ),
    ]
