# Generated by Django 4.1.10 on 2023-11-12 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0005_alter_medcine_is_active_alter_medcine_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medcine",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="medcine",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
