# Generated by Django 4.1.10 on 2023-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0007_alter_medcine_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="medcine",
            name="organization_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medcine",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
