# Generated by Django 4.1.10 on 2023-11-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0008_medcine_organization_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medcine",
            name="organization_location",
        ),
        migrations.RemoveField(
            model_name="medcine",
            name="organization_name",
        ),
    ]
