# Generated by Django 4.1.10 on 2023-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lungdiagnostic", "0012_alter_patient_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medcine",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="D:\\fin_de_etude\\data\\pfe\\back end\\application\\media",
            ),
        ),
    ]
